server:
  port: 8080
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: PracticeProject
  mustache:
    servlet:
      expose-request-attributes: 'true'
  main:
    allow-circular-references: true
jwt:
  secret: ${JWT_SECRET}
  lifetime: 30m
